#include "SystemAdmin.h"
#include "Course.h"
#include "Exceptions.h"
#include <iostream>
#include <iomanip>
#include <ctime>

using namespace std;

SystemAdmin::SystemAdmin(const string& n, int i) : User(n, i) {
    cout << "Success: " << n << " is registered as a System Admin!" << endl;
    addLog("System Admin " + n + " created.");
}

void SystemAdmin::displayDashboard() const {
    cout << "\n========== System Admin Portal ==========" << endl;
    cout << "Admin: " << getName() << " | ID: " << getID() << endl;
    cout << "Total Users in System: " << getTotalUsers() << endl;
    cout << "Total Admin Logs: " << systemLogs.size() << endl;
    cout << "Supervised Courses: " << supervisedCourses.size() << endl;
    cout << "========================================" << endl;
}

void SystemAdmin::addLog(const string& action) {
    time_t now = time(nullptr);
    struct tm* timeinfo = localtime(&now);
    char timestamp[100];
    strftime(timestamp, sizeof(timestamp), "%Y-%m-%d %H:%M:%S", timeinfo);
    
    string logEntry = "[" + string(timestamp) + "] " + getName() + ": " + action;
    systemLogs.push_back(logEntry);
    cout << "[LOG] " << logEntry << endl;
}

void SystemAdmin::viewSystemLogs() const {
    if (systemLogs.empty()) {
        cout << "\n[INFO] No system logs available.\n" << endl;
        return;
    }
    
    cout << "\n========== System Logs ==========" << endl;
    cout << setw(3) << "#" << setw(60) << "Action" << endl;
    cout << "---------------------------------" << endl;
    
    for (size_t i = 0; i < systemLogs.size(); ++i) {
        cout << setw(3) << (i + 1) << ". " << systemLogs[i] << endl;
    }
    cout << "=================================" << endl;
}

void SystemAdmin::generateSystemReport() const {
    cout << "\n========== SYSTEM REPORT ==========" << endl;
    cout << "Generated by: " << getName() << " (ID: " << getID() << ")" << endl;
    cout << "Total Users Created: " << getTotalUsers() << endl;
    cout << "Total Admin Logs: " << systemLogs.size() << endl;
    cout << "Courses Supervised: " << supervisedCourses.size() << endl;
    
    if (!systemLogs.empty()) {
        cout << "\nLatest 5 Activities:" << endl;
        size_t start = systemLogs.size() > 5 ? systemLogs.size() - 5 : 0;
        for (size_t i = start; i < systemLogs.size(); ++i) {
            cout << "  " << (i + 1) << ". " << systemLogs[i] << endl;
        }
    }
    cout << "===================================" << endl;
}

void SystemAdmin::deleteUser(const string& userType, int userId) {
    string logMsg = "Attempted to delete " + userType + " with ID " + std::to_string(userId);
    addLog(logMsg);
}

// NEW: Supervise a course
void SystemAdmin::superviseCourse(Course* c) {
    if (!c) {
        throw InvalidInputException("Cannot supervise a null course.");
    }
    
    // Check for duplicates
    for (auto* course : supervisedCourses) {
        if (course == c) {
            throw DuplicateEntityException("Course '" + c->getCourseName() + 
                "' is already supervised by this admin.");
        }
    }
    
    supervisedCourses.push_back(c);
    string logMsg = "Started supervising course: " + c->getCourseName();
    addLog(logMsg);
    cout << "[ADMIN] " << getName() << " is now supervising " << c->getCourseName() << endl;
}

// NEW: View supervised courses
void SystemAdmin::viewSupervisedCourses() const {
    if (supervisedCourses.empty()) {
        cout << "\n[INFO] " << getName() << " is not supervising any courses.\n" << endl;
        return;
    }
    
    cout << "\n========== Supervised Courses ==========" << endl;
    cout << "Admin: " << getName() << endl;
    for (size_t i = 0; i < supervisedCourses.size(); ++i) {
        cout << (i + 1) << ". " << supervisedCourses[i]->getCourseName() << endl;
    }
    cout << "========================================" << endl;
}